### ISSUE TITLE
Change title text for compilation date

### ISSUE THREAD

**Issue by aflaus** [af-lab/histone-catalogue#41]
Can we change the date line in the title text to read "Compiled on XXX" and use a smaller font.

I'm not quite sure where this is line encoded.

**Comment by carandraug** [comment]
I think the issue was opened because previously there used to be a date at the top of the document. This was the default Latex article title and the date was the compilation date. The issue was about making it clear that the date was the document build date and not the date of the data used in the analysis. We now have changed the document style and there's no longer a date on the title. So closing this.

The Compilation date is not that useful because it's used to infer how up to date the paper is. However, the date that matters is the data was downloaded from NCBI which is already the methods section.
