### ISSUE TITLE
Missing Bio/Tools/Phylo/PAML.pm in Ubuntu 18.04

### ISSUE THREAD

**Issue by aflaus** [af-lab/histone-catalogue#47]
Hi David

I just upgraded my virtual machine to 18.05 LTS but had a couple of gotchas:
1. Can't locate File::Which
Easily fixed by installing libfile-which-perl

2. Can't locate Bio/Tools/Phylo/PAML.pm
- bioperl is already the newest version (1.7.2-2).
- bioperl-run is already the newest version (1.7.1-3).
- libbio-eutilities-perl is already the newest version (1.75-3).

I'm guessing this is to do with https://metacpan.org/release/Bio-Tools-Phylo-PAML

Andrew.

**Comment by carandraug** [comment]
> 2. Can't locate Bio/Tools/Phylo/PAML.pm
>
> I'm guessing this is to do with https://metacpan.org/release/Bio-Tools-Phylo-PAML

Yes, Bio::Tools::Phylo::PAML is no longer part of bioperl-run, you need to install it separate and Ubuntu does not have it packaged.  Note that Clustalw and TCoffee were also removed from bioperl-run. See changes for latest release, version 1.7.2, https://metacpan.org/release/BioPerl-Run

The thing is that bioperl-run had everything that were bioperl interfaces to external programs in it. This meant that installing bioperl-run brought in a lot of dependencies that were tricky to install, even if you weren't interested in them.

At the moment those new packages are still dependent on bioperl-run because the abstract classes are still there, but that's not a problem for you at the moment because bioperl-run is still packaged in Ubuntu.

Anyway, this is not an issue for the histone-catalogue configure, because we check for the presence of the modules, not of the distributions.

**Comment by aflaus** [comment]
Unfortunately the check is failing with "Can't locate Bio/Tools/Phylo/PAML.pm"

**Comment by carandraug** [comment]
> Unfortunately the check is failing with "Can't locate Bio/Tools/Phylo/PAML.pm"

Yes. Because you don't have it installed. It's failing as it should. You installed bioperl-run but that module is no longer part of bioperl-run (for the reasons explained above). You need to install the Bio-Tools-Phylo-PAML distribution you refered in the first post.

This is not an issue with the histone catalogue.  The code is doing what it should, checking for the PAML module and not the bioperl-run distribution, and failing as it should because it's not installed.

**Comment by aflaus** [comment]
I'm still having a problem with this.

I seemed to install Bio-Tools-Phylo-PAML via cpan successfully but the check still fails.

Just to see how foolish I am, I tried installing Bio::Tools::Run::Phylo::PAML::Codeml thinking it would get the dependencies but this does not help.

---

$ scons --email=andrew.flaus@nuigalway.ie manuscript
[STUFF REMOVED]
Can't locate Bio/Tools/Phylo/PAML.pm in @INC (you may need to install the Bio::Tools::Phylo::PAML module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Bio/Tools/Run/Phylo/PAML/Codeml.pm line 104.
BEGIN failed--compilation aborted at /usr/share/perl5/Bio/Tools/Run/Phylo/PAML/Codeml.pm line 104.
Compilation failed in require.
BEGIN failed--compilation aborted.
Checking for perl module Bio::Tools::Run::Phylo::PAML::Codeml...(cached) no
Unable to find perl module Bio::Tools::Run::Phylo::PAML::Codeml.

$ cpan Bio-Tools-Phylo-PAML
Loading internal null logger. Install Log::Log4perl for logging messages

CPAN.pm requires configuration, but most of it can be done automatically.
If you answer 'no' below, you will enter an interactive dialog for each
configuration option instead.

Would you like to configure as much as possible automatically? [yes] yes
Use of uninitialized value $what in concatenation (.) or string at /usr/share/perl/5.26/App/Cpan.pm line 669, <STDIN> line 1.

Warning: You do not have write permission for Perl library directories.

To install modules, you need to configure a local Perl library directory or
escalate your privileges.  CPAN can help you by bootstrapping the local::lib
module or by configuring itself to use 'sudo' (if available).  You may also
resolve this problem manually if you need to customize your setup.

What approach do you want?  (Choose 'local::lib', 'sudo' or 'manual')
 [local::lib] sudo
Fetching with LWP:
http://www.cpan.org/authors/01mailrc.txt.gz
Reading '/home/histones/.cpan/sources/authors/01mailrc.txt.gz'
............................................................................DONE
Fetching with LWP:
http://www.cpan.org/modules/02packages.details.txt.gz
Reading '/home/histones/.cpan/sources/modules/02packages.details.txt.gz'
  Database was generated on Fri, 29 Jun 2018 16:17:03 GMT
............................................................................DONE
Fetching with LWP:
http://www.cpan.org/modules/03modlist.data.gz
Reading '/home/histones/.cpan/sources/modules/03modlist.data.gz'
DONE
Writing /home/histones/.cpan/Metadata

$ scons --email=andrew.flaus@nuigalway.ie manuscript
[STUFF REMOVED]
Can't locate Bio/Tools/Phylo/PAML.pm in @INC (you may need to install the Bio::Tools::Phylo::PAML module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /usr/share/perl5/Bio/Tools/Run/Phylo/PAML/Codeml.pm line 104.
BEGIN failed--compilation aborted at /usr/share/perl5/Bio/Tools/Run/Phylo/PAML/Codeml.pm line 104.
Compilation failed in require.
BEGIN failed--compilation aborted.
Checking for perl module Bio::Tools::Run::Phylo::PAML::Codeml...(cached) no
Unable to find perl module Bio::Tools::Run::Phylo::PAML::Codeml.

$ cpan Bio::Tools::Run::Phylo::PAML::Codeml
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/home/histones/.cpan/Metadata'
  Database was generated on Fri, 29 Jun 2018 16:17:03 GMT
Running install for module 'Bio::Tools::Run::Phylo::PAML::Codeml'
Fetching with LWP:
http://www.cpan.org/authors/id/C/CD/CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz
Fetching with LWP:
http://www.cpan.org/authors/id/C/CD/CDRAUG/CHECKSUMS
Checksum for /home/histones/.cpan/sources/authors/id/C/CD/CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz ok
Configuring C/CD/CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Warning: prerequisite Env::Path 0.18 not found.
Generating a Unix-style Makefile
Writing Makefile for Bio::Tools::Phylo::PAML
Writing MYMETA.yml and MYMETA.json
  CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for C/CD/CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz
---- Unsatisfied dependencies detected during ----
---- CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz ----
    Env::Path [build_requires]
Running install for module 'Env::Path'
Fetching with LWP:
http://www.cpan.org/authors/id/D/DS/DSB/Env-Path-0.19.tar.gz
Fetching with LWP:
http://www.cpan.org/authors/id/D/DS/DSB/CHECKSUMS
Checksum for /home/histones/.cpan/sources/authors/id/D/DS/DSB/Env-Path-0.19.tar.gz ok
Configuring D/DS/DSB/Env-Path-0.19.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Env::Path
Writing MYMETA.yml and MYMETA.json
  DSB/Env-Path-0.19.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for D/DS/DSB/Env-Path-0.19.tar.gz
  DSB/Env-Path-0.19.tar.gz
  make -- NOT OK
  No such file or directory
  CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz
  Has already been unwrapped into directory /home/histones/.cpan/build/Bio-Tools-Phylo-PAML-1.7.2-0
  CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz
  Has already been prepared
Running make for C/CD/CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz
Warning: Prerequisite 'Env::Path => 0.18' for 'CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz' failed when processing 'DSB/Env-Path-0.19.tar.gz' with 'make => NO'. Continuing, but chances to succeed are limited.
  CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz
  make -- NOT OK
  No such file or directory

$ sudo apt-get install libenv-path-perl
[installed ok]

$cpan Bio::Tools::Phylo::PAML
Loading internal null logger. Install Log::Log4perl for logging messages
Reading '/home/administrator/.cpan/Metadata'
  Database was generated on Fri, 29 Jun 2018 16:17:03 GMT
Running install for module 'Bio::Tools::Phylo::PAML'
Checksum for /home/administrator/.cpan/sources/authors/id/C/CD/CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz ok
Configuring C/CD/CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz with Makefile.PL
Checking if your kit is complete...
Looks good
Generating a Unix-style Makefile
Writing Makefile for Bio::Tools::Phylo::PAML
Writing MYMETA.yml and MYMETA.json
  CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz
  /usr/bin/perl Makefile.PL INSTALLDIRS=site -- OK
Running make for C/CD/CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz
  CDRAUG/Bio-Tools-Phylo-PAML-1.7.2.tar.gz
  make -- NOT OK
  No such file or directory

**Comment by carandraug** [comment]
As I mentioned by email, I'm trying to get this packaged in Debian.

I don't know why it's not working for you, and I don't usually install them with `cpan`. However, when I tried to run that, it worked for me so I don't know what's wrong with your system.  The only difference is that choose `local::lib` instead of `sudo`. This means that you will then have to run `scons PERL5LIB=/home/.../perl5/lib/perl ...`

**Comment by aflaus** [comment]
Succeeded in building manuscript after manually building latest PAML 4.9 and Bio/Tools/Phylo/PAML 1.7.3 from UCL and metacpan respectively.

Notable error about missing "evolver" in Bio/Tools/Phylo/PAML build led me to rebuild PAML. evolver is a PAML component that was indeed missing from /usr/bin although codeml and baseml were there. Is evolver correctly packaged in paml repository build?

**Comment by carandraug** [comment]
> Notable error about missing "evolver" in Bio/Tools/Phylo/PAML build led me to rebuild PAML. evolver is a PAML component that was indeed missing from /usr/bin although codeml and baseml were there. Is evolver correctly packaged in paml repository build?

The program surface evolve already has a binary named `evolve`. To avoid conflicts, debian renamed the `evolve` binary as `paml-evolve`. There's a directory with the original name in `/usr/lib/paml/bin/`. You can add it to your path. Alternative, you can set `PALMDIR` which bioperl will use when looking for `evolve` program. The solution I used in Debian packaging was to change the program name used internally https://salsa.debian.org/perl-team/modules/packages/libbio-tools-phylo-paml-perl/blob/master/debian/patches/evolver-program-name.patch

**Comment by aflaus** [comment]
I'm not clear why the Bio/Tools/Phylo/PAML build reported an error since paml-evolver was installed. Should I file a bug with the Bio/Tools/Phylo/PAML maintainer?

**Comment by carandraug** [comment]
> I'm not clear why the Bio/Tools/Phylo/PAML build reported an error since paml-evolver was installed.
> Should I file a bug with the Bio/Tools/Phylo/PAML maintainer?

No.

paml-evolver was installed, but Bioperl-PAML does not know that in your system evolver has been renamed to paml-evolver. And Bioper-PAML shouldn't have to guess, since in your system it could have been renamed anything. Maybe evover-paml, or paml_evolver, or anything else really.

So this really falls to whoever has knowledge of the system. If this is packaged in Debian, it would be up to the debian packager to set it up so it works. The new Bioperl-PAML debian package is patched so it looks for a program named paml-evolver (I guess it was also what was done when Bioperl-PAML was packaged as part of bioperl-run). If one does not use what is packaged by debian, then it falls to the sysadmin. The documentation of Debian's paml make note of the rename and suggest adding `/usr/lib/paml/bin/` to the path when evolver is needed. If one does it, then installing Bioperl-PAML from source should have work.

Anyway, this is now packaged in Debian and it should trickle down to the next ubuntu release.

I'm surprised you didn't have the same issue with tcoffee and clustalw since those have also been made separate bioperl packages. I'm guesing Ubuntu is doing something different. I will be packaging them for Debian as time permits anyway.

**Comment by carandraug** [comment]
> I'm surprised you didn't have the same issue with tcoffee and clustalw since those have also been made separate bioperl packages. I'm guesing Ubuntu is doing something different. I will be packaging them for Debian as time permits anyway.

These are now packaged in debian too and will eventually trickle down to Ubuntu:

https://packages.debian.org/sid/libbio-tools-run-alignment-clustalw-perl

https://packages.debian.org/sid/libbio-tools-run-alignment-tcoffee-perl
