### ISSUE TITLE
Check for epstopdf

### ISSUE THREAD

**Issue by aflaus** [af-lab/histone-catalogue#48]
Build failed on 18.04 with:
sh: 1: epstopdf: not found
scons: *** [figs/seqlogo_H2A_cds.pdf] Error 127
scons: building terminated because of errors.

Easy fix by installing texlive-font-utils

Probably should check for this at beginning of script?

**Comment by carandraug** [comment]
SCons should been checking for this https://github.com/af-lab/histone-catalogue/blob/master/SConstruct#L361

If that is not working I will need to take a deeper look on why.

**Comment by carandraug** [comment]
I pushed a fix for this but I believe this is a bug in SCons.
Basically, if boils down to SCons assuming that if `pdftex` is
installed (one of the most basic texlive components), then all of
texlive is available.

In our checks, we don't check if there's an `epstopdf` program in the
path since we don't actually use it.  Instead, we use SCons' PDF
builders so we need to check if `EPSTOPDF` is defined since that's
what SCons will use to convert eps files to pdf.

`EPSTOPDF` should not be defined if the program it points to does not
exist.  However, SCons is checking if `pdftex` exists when defining
that variable (possibly because both `pdftex` and `epstopdf` are part
of texlive, its Debian that splits texlive into smaller components).

So, if any texlive component is installed, then texlive-binaries will
be installed, and `EPSTOPDF` will be defined:

    $ scons
    [...]
    Checking for variable EPSTOPDF...(cached) no
    SCons EPSTOPDF not configured.  Do you have epstopdf installed (part of texlive)
    $ sudo apt install texlive-font-utils
    [...] # also installs texlive-binaries (which has pdftex)
    $ scons
    scons: Reading SConscript files ...
    Checking for variable EPSTOPDF...(cached) yes
    [...]
    $ sudo apt purge texlive-font-utils
    [...] # does not uninstall texlive-binaries (pdftex remains installed)
    $ scons
    [...]
    Checking for variable EPSTOPDF...(cached) yes
    [...]
    $ sudo apt purge texlive-binaries
    [...]
    $ scons
    Checking for variable EPSTOPDF...(cached) no
    SCons EPSTOPDF not configured.  Do you have epstopdf installed (part of texlive)

So I fixed this now by checking whether the program `EPSTOPDF` is
pointing to actually exists on the path.
